LOCAL_PATH := $(call my-dir)/../../

include $(CLEAR_VARS)

LOCAL_MODULE := pd

LOCAL_CFLAGS := -Wno-error -Wno-error=format-security -Wno-format-security
LOCAL_CFLAGS += -DMATCHING=0 -DPIRACYCHECKS=0 -DROM_SIZE=32 -DAVOID_UB=1 -D_LANGUAGE_C=1 -DPAL=0 -DVERSION=2
LOCAL_CFLAGS += -D__MOBILE__ -fsigned-char -fno-strict-aliasing -fno-inline-functions -fwrapv -DENGINE_NAME=\"perfect_dark\"
LOCAL_CFLAGS += -Wno-constant-conversion -Wno-implicit-const-int-float-conversion -Wno-address -Wno-empty-body -Wno-int-in-bool-context -Wno-misleading-indentation -Wno-missing-braces -Wno-multichar -Wno-tautological-compare -Wno-unused-but-set-variable -Wno-unused-value -Wno-unused-variable -Wno-pointer-sign

ifneq ($(filter arm64-v8a x86_64,$(TARGET_ARCH_ABI)),)
    LOCAL_CFLAGS += -DPLATFORM_64BIT=1
endif

LOCAL_CPPFLAGS += -std=c++20

LOCAL_CFLAGS += -O0 -g

# Version info defines (normally generated by CMake)
LOCAL_CFLAGS += -DVERSION_TARGET=\"android\" -DVERSION_ARCH=\"arm\" -DVERSION_ROMID=\"ntsc-final\" -DVERSION_BUILD=\"release\" -DVERSION_HASH=\"unknown\" -DVERSION_BRANCH=\"port-android\"

LOCAL_C_INCLUDES := $(LOCAL_PATH)/include \
                    $(LOCAL_PATH)/include/PR \
                    $(LOCAL_PATH)/src/include \
                    $(LOCAL_PATH)/src/lib/ultra/audio \
                    $(LOCAL_PATH)/port/include \
                    $(LOCAL_PATH)/src \
                    $(LOCAL_PATH)/src/generated/ntsc-final

LOCAL_C_INCLUDES += $(TOP_DIR)/ \
                    $(LOCAL_PATH)/../../Clibs_OpenTouch/alpha \
                    $(SDL_INCLUDE_PATHS) \
                    $(TOP_DIR)/MobileTouchControls \
                    $(TOP_DIR)/Clibs_OpenTouch \
                    $(TOP_DIR)/Clibs_OpenTouch/alpha

# Clibs_OpenTouch sources
LOCAL_SRC_FILES += ../../Clibs_OpenTouch/alpha/android_jni.cpp \
                   ../../Clibs_OpenTouch/alpha/touch_interface.cpp \
                   ../../Clibs_OpenTouch/touch_interface_base.cpp

# Perfect Dark sources
# Using shell find to match CMake's GLOB_RECURSE for src/game and port
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(shell find $(LOCAL_PATH)/src/game -name "*.c"))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(shell find $(LOCAL_PATH)/port -name "*.c"))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(shell find $(LOCAL_PATH)/port -name "*.cpp"))

# Android specific bridge (if exists)
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/src/android/*.c))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/src/android/*.cpp))

# Library sources (matching CMake GLOB)
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/src/lib/mp3/*.c))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/src/lib/naudio/*.c))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/src/lib/ultra/audio/*.c))
LOCAL_SRC_FILES += $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/src/lib/ultra/gu/*.c))

# Explicitly listed library files in CMake
LOCAL_SRC_FILES += src/lib/ultra/io/vimodentsclan1.c \
                   src/lib/ultra/io/vimodepallan1.c \
                   src/lib/ultra/io/vimodempallan1.c \
                   src/lib/ultra/io/vitbl.c \
                   src/lib/ailist.c \
                   src/lib/anim.c \
                   src/lib/args.c \
                   src/lib/audiodma.c \
                   src/lib/audiomgr.c \
                   src/lib/base.c \
                   src/lib/collision.c \
                   src/lib/debughud.c \
                   src/lib/dma.c \
                   src/lib/fault.c \
                   src/lib/joy.c \
                   src/lib/lib_2f490_c.c \
                   src/lib/lib_2fc60.c \
                   src/lib/lib_3e3e0.c \
                   src/lib/lib_04f60nb.c \
                   src/lib/lib_17ce0.c \
                   src/lib/lib_034d0.c \
                   src/lib/lib_39c80.c \
                   src/lib/lib_15850.c \
                   src/lib/mema.c \
                   src/lib/memp.c \
                   src/lib/model.c \
                   src/lib/modelasm_c.c \
                   src/lib/mp3.c \
                   src/lib/mtx_c.c \
                   src/lib/mtx.c \
                   src/lib/music.c \
                   src/lib/path.c \
                   src/lib/profile.c \
                   src/lib/rdp.c \
                   src/lib/rmon.c \
                   src/lib/rng_c.c \
                   src/lib/rzip_c.c \
                   src/lib/snd.c \
                   src/lib/speaker.c \
                   src/lib/varsinit.c \
                   src/lib/vi.c \
                   src/textureconfig.c

LOCAL_LDLIBS := -lEGL -ldl -llog -lz -lm -lc -lGLESv2
LOCAL_STATIC_LIBRARIES := logwritter
LOCAL_SHARED_LIBRARIES := touchcontrols SDL2 saffal

include $(BUILD_SHARED_LIBRARY)
